title : Pedro Bandeira
subtitle : Biomedical Engineer
#logo : path\to\logo
description : This portfolio brings together my work at the intersection of engineering, healthcare, and product development. It includes case studies, Biodesign-driven innovation projects, and intelligent computer vision solutions built for real users. My focus is to apply my technical knowledge into smart, innovative solutions that generate real impact into people and industry.
show_downloads : true
theme : jekyll-theme-midnight

